//+------------------------------------------------------------------+
//|                                                       donjai.mq5 |
//|                                      Based on ZigZag Hedge Logic |
//|                                          Generated by AI         |
//+------------------------------------------------------------------+
#property copyright "donjai EA"
#property link      ""
#property version   "1.08"

#include <Trade\Trade.mqh>
#include <Trade\PositionInfo.mqh>
#include <Trade\SymbolInfo.mqh>
#include <Trade\OrderInfo.mqh>

enum ENUM_ABCD_START_MODE
  {
   USE_ABCD_ELSE_BUY=0, // Use ABCD, otherwise BUY
   ALWAYS_BUY=1,        // Always BUY
   ALWAYS_SELL=2,       // Always SELL
   STRICT_ABCD=3        // Strict ABCD only
  };

enum ENUM_LOT_MODE
  {
   LOT_ADD=0, // ADD mode
   LOT_MUL=1  // MUL mode
  };
  
enum ENUM_ZZ_SIDE
  {
   ZZ_NONE=0,
   ZZ_BUY=1,
   ZZ_SELL=-1
  };

enum ENUM_ABCD_SIGNAL
  {
   ABCD_NONE=0,
   ABCD_BUY=1,
   ABCD_SELL=-1
  };

//--- Inputs
input string               InpGroup1                  = "--- Core Settings ---";
input bool                 InpAutoStart               = true;
input double               InpStartLot                = 0.01; // Back to 0.01 to prevent margin out
input ENUM_ABCD_START_MODE InpABCDStartMode           = USE_ABCD_ELSE_BUY;
input int                  InpStepPoints              = 300;  // 30 Pips gap
input int                  InpTimerSeconds            = 1;
input ulong                InpMagic                   = 20260210;

input string               InpGroup2                  = "--- Lot Progression ---";
input ENUM_LOT_MODE        InpLotMode                 = LOT_MUL;
input double               InpLotAdd                  = 0.01;
input double               InpLotMultiplier           = 1.5;  // Softer martingale (0.01 -> 0.02(rounded) -> 0.03 -> 0.05 -> 0.08)
input double               InpFirstOppLot             = 0.0;  // 0 = Auto
input int                  InpMaxCycles               = 6;    // Max 6 cycles
input double               InpMaxLotLimit             = 0.50; // Max out before blowing margin
input bool                 InpPauseOnMaxLot           = true;

input string               InpGroup3                  = "--- Risk & Money Management ---";
input bool                 InpCloseAllOnProfit        = true; // Turn ON for auto-profit
input double               InpProfitTargetMoney       = 50.0; // Target 50 cents (~$0.50) per cycle due to smaller lot
input bool                 InpCloseAllOnLoss          = true; // Turn ON to protect capital
input double               InpLossLimitMoney          = 2000.0; // Protect 2000 cents max DD (~$20) (checked as -2000.0)
input int                  InpSL_Points               = 0;
input int                  InpTP_Points               = 0;

input string               InpGroup4                  = "--- Anti-Sideway & Follow Price ---";
input int                  InpSidewayMinATRPoints     = 100;  // Activate sideway if < 100 points
input int                  InpATRPeriod               = 14;
input bool                 InpFollowPriceForPending   = true; // ON to drag order
input int                  InpPendingRepriceThresholdPoints = 15;

input string               InpGroup5                  = "--- ZigZag ABCD Signal ---";
input ENUM_TIMEFRAMES      InpABCDTimeframe           = PERIOD_H1; // H1 gives steadier trend
input int                  InpABCDLookbackBars        = 200;
input int                  InpABCDConfirmBars         = 1;
input int                  InpABCDMinLegPoints        = 100; // Filter small noises
input int                  InpZigZagDepth             = 12;
input int                  InpZigZagDeviation         = 5;
input int                  InpZigZagBackstep          = 3;
input string               InpZigZagPath              = "Examples\\ZigZag"; 

input string               InpGroup6                  = "--- System ---";
input bool                 InpUseTerminalGlobalVar    = true;
input bool                 InpDebugPrint              = true;
input bool                 InpLotAddShadowEnabled     = true; // USE shadow in Sideway

input string               InpGroup7                  = "--- Shadow & Trailing Module ---";
input int                  InpShadowTrailingStopPoints= 50;
input int                  InpShadowTrailingStepPoints= 10;

//--- Global Objects
CTrade         trade;
CPositionInfo  posInfo;
CSymbolInfo    symInfo;
COrderInfo     orderInfo;

int zigzagHandle = INVALID_HANDLE;
int atrHandle = INVALID_HANDLE;

//--- State Variables
double gUpperPrice = 0.0;
double gLowerPrice = 0.0;
ENUM_ZZ_SIDE gLastTriggered = ZZ_NONE;
double gNextLot = 0.0;
int gCycles = 0;
bool gStarted = false;
bool gPendingCloseAll = false;
bool gMarketWasClosed = false;
ENUM_ABCD_SIGNAL gAbcdSignal = ABCD_NONE;
bool gPausedBySideway = false;
bool gPausedByMaxLot = false;

//+------------------------------------------------------------------+
//| Utility Functions                                                |
//+------------------------------------------------------------------+
void DPrint(string msg) { if(InpDebugPrint) Print(msg); }

string GVBase() { return "ZZH2LV8_" + _Symbol + "_" + IntegerToString(InpMagic) + "_"; }

ulong LotAddShadowMagic() { return InpMagic + 1; }

double NormalizeLot(double lots)
  {
   double step = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   double min = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double max = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
   double l = MathRound(lots / step) * step;
   if(l < min) l = min;
   if(l > max) l = max;
   return l;
  }

double GetPipsMultiplier()
  {
   int digits = (int)SymbolInfoInteger(_Symbol, SYMBOL_DIGITS);
   if(digits == 5 || digits == 3) return 10.0 * _Point;
   else return _Point;
  }

double PriceByPoints(double price, int points, bool up)
  {
   double pipsMult = GetPipsMultiplier();
   if(up) return price + (points * pipsMult);
   return price - (points * pipsMult);
  }

bool IsTradeAllowedNow()
  {
   if(!TerminalInfoInteger(TERMINAL_TRADE_ALLOWED)) return false;
   if(!MQLInfoInteger(MQL_TRADE_ALLOWED)) return false;
   long mode = SymbolInfoInteger(_Symbol, SYMBOL_TRADE_MODE);
   if(mode == SYMBOL_TRADE_MODE_DISABLED || mode == SYMBOL_TRADE_MODE_CLOSEONLY) return false;
   if(IsStopped()) return false;
   return true;
  }

int PendingRepriceThresholdPts()
  {
   if(InpPendingRepriceThresholdPoints > 0) return InpPendingRepriceThresholdPoints;
   int threshold = InpStepPoints / 5;
   return threshold < 10 ? 10 : threshold;
  }

//+------------------------------------------------------------------+
//| Position & Order Counting Functions                              |
//+------------------------------------------------------------------+
int CountPositionsByMagicValue(ulong magic)
  {
   int count = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      if(posInfo.SelectByIndex(i))
         if(posInfo.Magic() == magic && posInfo.Symbol() == _Symbol)
            count++;
     }
   return count;
  }

int CountPositionsByMagic()
  {
   return CountPositionsByMagicValue(InpMagic);
  }

int CountManagedPositions()
  {
   return CountPositionsByMagicValue(InpMagic) + CountPositionsByMagicValue(LotAddShadowMagic());
  }

bool IsFlatNow()
  {
   return CountManagedPositions() == 0;
  }

double FloatingProfitByMagicValue(ulong magic)
  {
   double profit = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      if(posInfo.SelectByIndex(i))
        {
         if(posInfo.Magic() == magic && posInfo.Symbol() == _Symbol)
           {
            profit += posInfo.Profit() + posInfo.Swap();
           }
        }
     }
   return profit;
  }

double FloatingProfitByMagic()
  {
   return FloatingProfitByMagicValue(InpMagic) + FloatingProfitByMagicValue(LotAddShadowMagic());
  }

bool GetLastPosition(ENUM_ZZ_SIDE &side, double &openPrice, double &vol)
  {
   ulong lastTicket = 0;
   bool found = false;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      if(posInfo.SelectByIndex(i))
        {
         if(posInfo.Magic() == InpMagic && posInfo.Symbol() == _Symbol)
           {
            if(posInfo.Ticket() > lastTicket)
              {
               lastTicket = posInfo.Ticket();
               side = (posInfo.PositionType() == POSITION_TYPE_BUY) ? ZZ_BUY : ZZ_SELL;
               openPrice = posInfo.PriceOpen();
               vol = posInfo.Volume();
               found = true;
              }
           }
        }
     }
   return found;
  }

bool PendingExistsByMagic(long wantType, ulong magic, ulong &ticket, double &price)
  {
   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      ulong t = OrderGetTicket(i);
      if(OrderSelect(t))
        {
         if(OrderGetInteger(ORDER_MAGIC) == magic && OrderGetString(ORDER_SYMBOL) == _Symbol)
           {
            if(OrderGetInteger(ORDER_TYPE) == wantType)
              {
               ticket = t;
               price = OrderGetDouble(ORDER_PRICE_OPEN);
               return true;
              }
           }
        }
     }
   return false;
  }

bool PendingExists(long wantType, ulong &ticket, double &price)
  {
   return PendingExistsByMagic(wantType, InpMagic, ticket, price);
  }

//+------------------------------------------------------------------+
//| Close & Cancel Functions                                         |
//+------------------------------------------------------------------+
void CancelAllPendingsByMagicValue(ulong magic)
  {
   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      ulong ticket = OrderGetTicket(i);
      if(OrderSelect(ticket))
        {
         if(OrderGetInteger(ORDER_MAGIC) == magic && OrderGetString(ORDER_SYMBOL) == _Symbol)
           {
            trade.OrderDelete(ticket);
           }
        }
     }
  }

void CancelAllPendingsByMagic()
  {
   CancelAllPendingsByMagicValue(InpMagic);
  }

void CancelAllManagedPendings()
  {
   CancelAllPendingsByMagicValue(InpMagic);
   CancelAllPendingsByMagicValue(LotAddShadowMagic());
  }

void CloseAllPositionsByMagicValue(ulong magic)
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      if(posInfo.SelectByIndex(i))
        {
         if(posInfo.Magic() == magic && posInfo.Symbol() == _Symbol)
           {
            trade.PositionClose(posInfo.Ticket());
           }
        }
     }
  }

void CloseAllManagedPositions()
  {
   CloseAllPositionsByMagicValue(InpMagic);
   CloseAllPositionsByMagicValue(LotAddShadowMagic());
  }

void ResetSequenceStateIfFlat(string reason)
  {
   if(!IsFlatNow()) return;
   
   // Avoid redundant resets which can cause stack overflows or log spam
   if(!gStarted && gCycles == 0 && gLastTriggered == ZZ_NONE) return;
   
   CancelAllManagedPendings();
   gStarted = false;
   gCycles = 0;
   gLastTriggered = ZZ_NONE;
   gUpperPrice = 0.0;
   gLowerPrice = 0.0;
   gNextLot = InpStartLot;
   gPendingCloseAll = false;
   gPausedByMaxLot = false;
   DPrint("Sequence reset: " + reason);
   SaveState();
  }

void HandleMarketOpenClose()
  {
   bool isOpen = (SymbolInfoDouble(_Symbol, SYMBOL_ASK) > 0 && SymbolInfoDouble(_Symbol, SYMBOL_BID) > 0);
   if(!isOpen && !gMarketWasClosed)
     {
      DPrint("Market closed.");
      gMarketWasClosed = true;
     }
   else if(isOpen && gMarketWasClosed)
     {
      DPrint("Market reopened.");
      gMarketWasClosed = false;
      if(IsFlatNow()) ResetSequenceStateIfFlat("Market Reopen");
      else if(gPendingCloseAll) CheckProfitLossCloseAll();
      else RebuildFromExisting();
     }
  }

void RebuildFromExisting()
  {
   int count = CountPositionsByMagic();
   if(count > 0)
     {
      ENUM_ZZ_SIDE side;
      double openPrice, vol;
      if(GetLastPosition(side, openPrice, vol))
        {
         // Find Upper/Lower from existing rules
         if(side == ZZ_BUY)
           {
            gUpperPrice = openPrice;
            gLowerPrice = gUpperPrice - (InpStepPoints * GetPipsMultiplier());
           }
         else
           {
            gLowerPrice = openPrice;
            gUpperPrice = gLowerPrice + (InpStepPoints * GetPipsMultiplier());
           }
         gLastTriggered = side;
         gNextLot = GetNextLot(vol);
         gStarted = true;
         gCycles = count;
         SaveState();
         MaintainOppositePending();
        }
     }
  }

//+------------------------------------------------------------------+
//| Anti-Sideway & ATR Guard                                         |
//+------------------------------------------------------------------+
void EnsureAtrHandle()
  {
   if(atrHandle == INVALID_HANDLE)
      atrHandle = iATR(_Symbol, PERIOD_CURRENT, InpATRPeriod);
  }

double CurrentATRPoints()
  {
   EnsureAtrHandle();
   if(atrHandle == INVALID_HANDLE) return 0;
   double atr[];
   if(CopyBuffer(atrHandle, 0, 1, 1, atr) > 0)
      return atr[0] / GetPipsMultiplier();
   return 0;
  }

bool IsSidewayNow()
  {
   if(InpSidewayMinATRPoints <= 0) return false;
   double atrPts = CurrentATRPoints();
   bool isSideway = (atrPts < InpSidewayMinATRPoints && atrPts > 0);
   if(isSideway && !gPausedBySideway) DPrint("Entered Sideway Mode (ATR: " + DoubleToString(atrPts, 1) + ")");
   if(!isSideway && gPausedBySideway) DPrint("Exited Sideway Mode");
   gPausedBySideway = isSideway;
   return isSideway;
  }

//+------------------------------------------------------------------+
//| ABCD Structure-Break Signal (ZigZag)                             |
//+------------------------------------------------------------------+
void EnsureZigZagHandle()
  {
   if(zigzagHandle == INVALID_HANDLE)
      zigzagHandle = iCustom(_Symbol, InpABCDTimeframe, InpZigZagPath, InpZigZagDepth, InpZigZagDeviation, InpZigZagBackstep);
  }

void UpdateAbcdSignalIfNeeded()
  {
   // Throttle to avoid heavy calculation every tick
   static datetime lastBar = 0;
   datetime currentBar = (datetime)SeriesInfoInteger(_Symbol, InpABCDTimeframe, SERIES_LASTBAR_DATE);
   if(currentBar == lastBar && InpABCDStartMode == USE_ABCD_ELSE_BUY) return;
   lastBar = currentBar;

   if(InpABCDStartMode == ALWAYS_BUY) { gAbcdSignal = ABCD_BUY; return; }
   if(InpABCDStartMode == ALWAYS_SELL) { gAbcdSignal = ABCD_SELL; return; }
   
   EnsureZigZagHandle();
   if(zigzagHandle == INVALID_HANDLE) 
     {
      gAbcdSignal = (InpABCDStartMode == STRICT_ABCD) ? ABCD_NONE : ABCD_BUY;
      return;
     }

   double zz[];
   if(CopyBuffer(zigzagHandle, 0, InpABCDConfirmBars, InpABCDLookbackBars, zz) <= 0) return;
   
   // Find last 4 pivots
   double pivots[4];
   int pCount = 0;
   for(int i = ArraySize(zz) - 1; i >= 0 && pCount < 4; i--)
     {
      if(zz[i] > 0)
        {
         pivots[pCount] = zz[i];
         pCount++;
        }
     }
     
   if(pCount < 4) 
     {
      gAbcdSignal = (InpABCDStartMode == STRICT_ABCD) ? ABCD_NONE : ABCD_BUY;
      return;
     }

   double D = pivots[0]; // Newest
   double C = pivots[1];
   double B = pivots[2];
   double A = pivots[3]; // Oldest

   double minLeg = InpABCDMinLegPoints * GetPipsMultiplier();
   
   // Bullish: A(high) -> B(low) -> C(lower high) -> D(lower low) -> wait, Bullish break means price goes UP after D
   // Actually, standard ABCD Bullish: down -> up -> down -> breaking up?
   // Let's implement a simple structure detector
   bool isBullish = (A > B && C > B && C < A && D < C && D < B);
   bool isBearish = (A < B && C < B && C > A && D > C && D > B);

   if(isBullish && MathAbs(A-B)>minLeg && MathAbs(C-B)>minLeg && MathAbs(C-D)>minLeg)
      gAbcdSignal = ABCD_BUY;
   else if(isBearish && MathAbs(B-A)>minLeg && MathAbs(B-C)>minLeg && MathAbs(D-C)>minLeg)
      gAbcdSignal = ABCD_SELL;
   else
      gAbcdSignal = (InpABCDStartMode == STRICT_ABCD) ? ABCD_NONE : ABCD_BUY;
  }

//+------------------------------------------------------------------+
//| Lot Progression                                                  |
//+------------------------------------------------------------------+
void ApplyMaxLotLimit(double &lots, bool &exceeded)
  {
   exceeded = false;
   if(InpMaxLotLimit > 0 && lots > InpMaxLotLimit)
     {
      lots = InpMaxLotLimit;
      exceeded = true;
     }
  }

double GetNextLot(double lastVol)
  {
   double nextLot = lastVol;
   if(InpLotMode == LOT_ADD) nextLot += InpLotAdd;
   else if(InpLotMode == LOT_MUL) nextLot *= InpLotMultiplier;
   
   bool exceeded;
   ApplyMaxLotLimit(nextLot, exceeded);
   if(exceeded && InpPauseOnMaxLot) gPausedByMaxLot = true;
     
   return NormalizeLot(nextLot);
  }

double GetFirstOppLot()
  {
   if(InpFirstOppLot > 0) return NormalizeLot(InpFirstOppLot);
   double firstOppLot = InpStartLot;
   if(InpLotMode == LOT_ADD) firstOppLot += InpLotAdd;
   else if(InpLotMode == LOT_MUL) firstOppLot *= InpLotMultiplier;
   return NormalizeLot(firstOppLot);
  }

//+------------------------------------------------------------------+
//| SL / TP                                                          |
//+------------------------------------------------------------------+
void ApplySLTPForOpenedPosition(ENUM_ZZ_SIDE side, double openPrice, ulong ticket)
  {
   if(InpSL_Points == 0 && InpTP_Points == 0) return;
   
   double sl = 0, tp = 0;
   if(side == ZZ_BUY)
     {
      if(InpSL_Points > 0) sl = openPrice - (InpSL_Points * GetPipsMultiplier());
      if(InpTP_Points > 0) tp = openPrice + (InpTP_Points * GetPipsMultiplier());
     }
   else if(side == ZZ_SELL)
     {
      if(InpSL_Points > 0) sl = openPrice + (InpSL_Points * GetPipsMultiplier());
      if(InpTP_Points > 0) tp = openPrice - (InpTP_Points * GetPipsMultiplier());
     }
     
   trade.PositionModify(ticket, sl, tp);
  }

//+------------------------------------------------------------------+
//| Core Trading Logic                                               |
//+------------------------------------------------------------------+
double DesiredOppositePendingPrice(ENUM_ZZ_SIDE lastSide)
  {
   if(!InpFollowPriceForPending)
      return (lastSide == ZZ_BUY) ? gLowerPrice : gUpperPrice;
      
   symInfo.RefreshRates();
   if(lastSide == ZZ_BUY)
     {
      double calculatedPrice = symInfo.Bid() - (InpStepPoints * GetPipsMultiplier());
      // We are holding BUY, pending is SELL STOP.
      // If price goes UP (profit), calculatedPrice goes UP.
      // We want the pending order to trail UP. It can NEVER go DOWN (creeping toward a loss).
      return MathMax(gLowerPrice, calculatedPrice);
     }
   else
     {
      double calculatedPrice = symInfo.Ask() + (InpStepPoints * GetPipsMultiplier());
      // We are holding SELL, pending is BUY STOP.
      // If price goes DOWN (profit), calculatedPrice goes DOWN.
      // We want the pending order to trail DOWN. It can NEVER go UP (creeping toward a loss).
      return MathMin(gUpperPrice, calculatedPrice); 
     }
  }

void PlaceOppositeStop(ENUM_ZZ_SIDE lastSide, double lots)
  {
   if(!IsTradeAllowedNow()) return;
   if(IsSidewayNow()) return; // ZZH2L_MaintainSidewayCounterOrders handles sideway instead
   if(gPausedByMaxLot) return;
   
   if(CountPositionsByMagic() != gCycles) return; // Prevent async race condition (e.g. pending triggered but OnTradeTrans not yet updated)
   
   lots = NormalizeLot(lots);
   long wantType = (lastSide == ZZ_BUY) ? ORDER_TYPE_SELL_STOP : ORDER_TYPE_BUY_STOP;
   
   // Sync pending logic
   ulong existingTicket; double existingPrice;
   if(PendingExists(wantType, existingTicket, existingPrice))
     {
      double desiredPrice = DesiredOppositePendingPrice(lastSide);
      if(MathAbs(existingPrice - desiredPrice) / GetPipsMultiplier() > PendingRepriceThresholdPts())
        {
         if(trade.OrderModify(existingTicket, desiredPrice, 0, 0, ORDER_TIME_GTC, 0))
           {
            // Ratchet the bounds to the new desired price so it doesn't snap back
            if(lastSide == ZZ_BUY) gLowerPrice = desiredPrice;
            else gUpperPrice = desiredPrice;
            SaveState();
           }
        }
      return;
     }

   // Place new
   CancelAllPendingsByMagic(); // Clean duplicate/wrong types
   symInfo.RefreshRates();
   
   if(lastSide == ZZ_BUY)
     {
      double price = DesiredOppositePendingPrice(lastSide);
      if(symInfo.Bid() > price)
        {
         if(trade.SellStop(lots, price, _Symbol, 0, 0, ORDER_TIME_GTC, 0, "Opposite Sell Stop"))
           {
            if(InpFollowPriceForPending) { gLowerPrice = price; SaveState(); }
           }
        }
      else
        {
         static datetime waitSell = 0;
         if(waitSell == 0) waitSell = TimeCurrent();
         else if(TimeCurrent() - waitSell >= 3) // Wait 3s to ensure it's not just a delayed MT5 sync
           {
            trade.Sell(lots, _Symbol, symInfo.Bid(), 0, 0, "Fast Trigger Sell"); // Safety if dropped fast
            waitSell = 0;
           }
        }
     }
   else if(lastSide == ZZ_SELL)
     {
      double price = DesiredOppositePendingPrice(lastSide);
      if(symInfo.Ask() < price)
        {
         if(trade.BuyStop(lots, price, _Symbol, 0, 0, ORDER_TIME_GTC, 0, "Opposite Buy Stop"))
           {
            if(InpFollowPriceForPending) { gUpperPrice = price; SaveState(); }
           }
        }
      else
        {
         static datetime waitBuy = 0;
         if(waitBuy == 0) waitBuy = TimeCurrent();
         else if(TimeCurrent() - waitBuy >= 3) // Wait 3s to ensure it's not just a delayed MT5 sync
           {
            trade.Buy(lots, _Symbol, symInfo.Ask(), 0, 0, "Fast Trigger Buy"); // Safety if spiked fast
            waitBuy = 0;
           }
        }
     }
  }

void StartSequence()
  {
   if(!IsTradeAllowedNow()) return;
   if(IsSidewayNow()) return;
   
   UpdateAbcdSignalIfNeeded();
   if(gAbcdSignal == ABCD_NONE) return;
   
   symInfo.RefreshRates();
   double ask = symInfo.Ask();
   double bid = symInfo.Bid();
   
   if(gAbcdSignal == ABCD_BUY)
     {
      gUpperPrice = ask;
      gLowerPrice = ask - (InpStepPoints * GetPipsMultiplier());
      if(trade.Buy(InpStartLot, _Symbol, ask, 0, 0, "Sequence Start Buy"))
        {
         gLastTriggered = ZZ_BUY;
         gNextLot = GetFirstOppLot();
         gCycles = 1; // Wait for transaction to increment, but assume 1 initially to prevent race
         SaveState();
         // Initial stop placement handled by OnTradeTransaction after position confirmation
        }
     }
   else if(gAbcdSignal == ABCD_SELL)
     {
      gLowerPrice = bid;
      gUpperPrice = bid + (InpStepPoints * GetPipsMultiplier());
      if(trade.Sell(InpStartLot, _Symbol, bid, 0, 0, "Sequence Start Sell"))
        {
         gLastTriggered = ZZ_SELL;
         gNextLot = GetFirstOppLot();
         gCycles = 1;
         SaveState();
        }
     }
     
   gStarted = true;
   SaveState();
  }

void MaintainOppositePending()
  {
   if(IsFlatNow()) 
     {
      // Rely on the main event loops (OnTick, OnTimer) to handle reset
      return;
     }
   if(IsSidewayNow())
     {
      CancelAllPendingsByMagic();
      if(InpLotAddShadowEnabled) ZZH2L_MaintainSidewayCounterOrders();
      return;
     }
   if(gPausedByMaxLot)
     {
      CancelAllPendingsByMagic();
      return;
     }
     
   if(gLastTriggered != ZZ_NONE && gNextLot > 0)
     {
      PlaceOppositeStop(gLastTriggered, gNextLot);
     }
     
   // Delete duplicates
   int pendingCount = 0;
   ulong lastTicket = 0;
   for(int i = OrdersTotal() - 1; i >=0 ; i--)
     {
      ulong ticket = OrderGetTicket(i);
      if(OrderSelect(ticket))
        {
         if(OrderGetInteger(ORDER_MAGIC) == InpMagic && OrderGetString(ORDER_SYMBOL) == _Symbol)
           {
            pendingCount++;
            if(pendingCount > 1) trade.OrderDelete(ticket); // delete older duplicates
            else lastTicket = ticket;
           }
        }
     }
  }

void ZZH2L_MaintainSidewayCounterOrders()
  {
   if(CountPositionsByMagicValue(LotAddShadowMagic()) > 0) return; // Allow only one active shadow position at a time
   
   // In sideway, place limits instead using ShadowMagic
   ulong tic; double prc;
   CTrade shadowTrade;
   shadowTrade.SetExpertMagicNumber(LotAddShadowMagic());
   
   if(gLastTriggered == ZZ_BUY && !PendingExistsByMagic(ORDER_TYPE_BUY_LIMIT, LotAddShadowMagic(), tic, prc))
     {
      symInfo.RefreshRates();
      double price = gLowerPrice;
      if(symInfo.Ask() > price) shadowTrade.BuyLimit(gNextLot, price, _Symbol, 0, 0, ORDER_TIME_GTC, 0, "Shadow Buy Limit (Sideway)");
      else shadowTrade.Buy(gNextLot, _Symbol, symInfo.Ask(), 0, 0, "Shadow Buy Triggered");
     }
   else if(gLastTriggered == ZZ_SELL && !PendingExistsByMagic(ORDER_TYPE_SELL_LIMIT, LotAddShadowMagic(), tic, prc))
     {
      symInfo.RefreshRates();
      double price = gUpperPrice;
      if(symInfo.Bid() < price) shadowTrade.SellLimit(gNextLot, price, _Symbol, 0, 0, ORDER_TIME_GTC, 0, "Shadow Sell Limit (Sideway)");
      else shadowTrade.Sell(gNextLot, _Symbol, symInfo.Bid(), 0, 0, "Shadow Sell Triggered");
     }
  }

void ZZH2L_ManageLotAddTrailingStop()
  {
   if(!InpLotAddShadowEnabled) return;
   if(InpShadowTrailingStopPoints <= 0) return;
   
   symInfo.RefreshRates();
   double bid = symInfo.Bid();
   double ask = symInfo.Ask();
   
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      if(posInfo.SelectByIndex(i))
        {
         if(posInfo.Magic() == LotAddShadowMagic() && posInfo.Symbol() == _Symbol)
           {
            ulong t = posInfo.Ticket();
            double openPrice = posInfo.PriceOpen();
            double sl = posInfo.StopLoss();
            double tp = posInfo.TakeProfit();
            
            if(posInfo.PositionType() == POSITION_TYPE_BUY)
              {
               if(bid - openPrice > InpShadowTrailingStopPoints * GetPipsMultiplier())
                 {
                  double newsl = bid - (InpShadowTrailingStopPoints * GetPipsMultiplier());
                  if(sl == 0.0 || newsl > sl + (InpShadowTrailingStepPoints * GetPipsMultiplier()))
                    {
                     trade.PositionModify(t, newsl, tp);
                    }
                 }
              }
            else if(posInfo.PositionType() == POSITION_TYPE_SELL)
              {
               if(openPrice - ask > InpShadowTrailingStopPoints * GetPipsMultiplier())
                 {
                  double newsl = ask + (InpShadowTrailingStopPoints * GetPipsMultiplier());
                  if(sl == 0.0 || newsl < sl - (InpShadowTrailingStepPoints * GetPipsMultiplier()))
                    {
                     trade.PositionModify(t, newsl, tp);
                    }
                 }
              }
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| Risk Management                                                  |
//+------------------------------------------------------------------+
void CheckProfitLossCloseAll()
  {
   if(!InpCloseAllOnProfit && !InpCloseAllOnLoss) return;
   
   double totalFloat = FloatingProfitByMagic();
   
   bool closeCondition = false;
   if(InpCloseAllOnProfit && totalFloat >= InpProfitTargetMoney) closeCondition = true;
   
   double safeLossLimit = InpLossLimitMoney;
   if(safeLossLimit > 0) safeLossLimit = -safeLossLimit; // Ensure it is treated as a negative boundary
   
   if(InpCloseAllOnLoss && totalFloat <= safeLossLimit) closeCondition = true;
   
   if(closeCondition)
     {
      if(!TerminalInfoInteger(TERMINAL_TRADE_ALLOWED))
        {
         gPendingCloseAll = true;
         return;
        }
        
      CancelAllManagedPendings();
      CloseAllManagedPositions();
      gPendingCloseAll = false;
     }
  }

//+------------------------------------------------------------------+
//| Main Events                                                      |
//+------------------------------------------------------------------+
int OnInit()
  {
   symInfo.Name(_Symbol);
   trade.SetExpertMagicNumber(InpMagic);
   
   if(InpUseTerminalGlobalVar) LoadState();
     
   if(IsFlatNow()) 
     {
      ResetSequenceStateIfFlat("OnInit: flat");
     }
   else 
     {
      RebuildFromExisting();
     }
     
   EventSetTimer(InpTimerSeconds);
   
   if(InpAutoStart && !gStarted) StartSequence();
     
   return(INIT_SUCCEEDED);
  }

void OnDeinit(const int reason)
  {
   if(InpUseTerminalGlobalVar) SaveState();
   EventKillTimer();
   if(zigzagHandle != INVALID_HANDLE) IndicatorRelease(zigzagHandle);
   if(atrHandle != INVALID_HANDLE) IndicatorRelease(atrHandle);
  }

void OnTimer()
  {
   HandleMarketOpenClose();
   
   if(IsFlatNow() && gStarted) 
     {
      ResetSequenceStateIfFlat("OnTimer: flat detected (clearing)");
     }
     
   UpdateAbcdSignalIfNeeded();
   ZZH2L_ManageLotAddTrailingStop();
   
   if(gPendingCloseAll) CheckProfitLossCloseAll();
      
   MaintainOppositePending();
  }

void OnTick()
  {
   if(!symInfo.RefreshRates()) return;
   
   HandleMarketOpenClose();
   
   if(IsFlatNow() && gStarted) 
     {
      ResetSequenceStateIfFlat("OnTick: flat detected (clearing)");
     }
     
   UpdateAbcdSignalIfNeeded();
   ZZH2L_ManageLotAddTrailingStop();
   
   if(InpAutoStart && IsFlatNow() && !gStarted)
      StartSequence();
      
   if(gPendingCloseAll) return;
   
   if(InpMaxCycles > 0 && gCycles >= InpMaxCycles && !IsFlatNow())
     {
      CancelAllManagedPendings();
      CheckProfitLossCloseAll();
     }
     
   if(!IsFlatNow()) 
     {
      CheckProfitLossCloseAll();
      MaintainOppositePending();
     }
  }

void OnTradeTransaction(const MqlTradeTransaction &trans, const MqlTradeRequest &request, const MqlTradeResult &result)
  {
   if(trans.type == TRADE_TRANSACTION_DEAL_ADD)
     {
      ulong ticket = trans.deal;
      if(HistoryDealSelect(ticket))
        {
         if(HistoryDealGetInteger(ticket, DEAL_MAGIC) == InpMagic && HistoryDealGetString(ticket, DEAL_SYMBOL) == _Symbol)
           {
            long entry = HistoryDealGetInteger(ticket, DEAL_ENTRY);
            if(entry == DEAL_ENTRY_IN)
              {
               long type = HistoryDealGetInteger(ticket, DEAL_TYPE);
               double vol = HistoryDealGetDouble(ticket, DEAL_VOLUME);
               double price = HistoryDealGetDouble(ticket, DEAL_PRICE);
               ulong posTicket = HistoryDealGetInteger(ticket, DEAL_POSITION_ID);
               
               if(type == DEAL_TYPE_BUY)
                 {
                  gLastTriggered = ZZ_BUY;
                  gUpperPrice = price; // Anchor the new grid bound based on execution
                  gLowerPrice = price - (InpStepPoints * GetPipsMultiplier());
                 }
               else if(type == DEAL_TYPE_SELL)
                 {
                  gLastTriggered = ZZ_SELL;
                  gLowerPrice = price; // Anchor the new grid bound based on execution
                  gUpperPrice = price + (InpStepPoints * GetPipsMultiplier());
                 }
               
               // Count logical cycles. It starts at cycle 1 for the first trigger.
               int actualCount = CountPositionsByMagic();
               // Update cycle count smoothly preventing double counts if transactions hit late
               if (actualCount > gCycles) gCycles = actualCount; 
               else if (gCycles == 0 && actualCount == 1) gCycles = 1; 

               ApplySLTPForOpenedPosition(gLastTriggered, price, posTicket);
               
               gNextLot = GetNextLot(vol);
               
               if(InpMaxCycles > 0 && gCycles >= InpMaxCycles)
                 {
                  CancelAllPendingsByMagic();
                  SaveState();
                  return;
                 }
                 
               PlaceOppositeStop(gLastTriggered, gNextLot);
               SaveState();
              }
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| State Persistence                                                |
//+------------------------------------------------------------------+
void SaveState()
  {
   if(!InpUseTerminalGlobalVar) return;
   GlobalVariableSet(GVBase() + "upper", gUpperPrice);
   GlobalVariableSet(GVBase() + "lower", gLowerPrice);
   GlobalVariableSet(GVBase() + "nextlot", gNextLot);
   GlobalVariableSet(GVBase() + "cycles", (double)gCycles);
   GlobalVariableSet(GVBase() + "last", (double)gLastTriggered);
   GlobalVariableSet(GVBase() + "started", gStarted ? 1.0 : 0.0);
   GlobalVariableSet(GVBase() + "pclose", gPendingCloseAll ? 1.0 : 0.0);
  }

void LoadState()
  {
   if(!InpUseTerminalGlobalVar) return;
   if(GlobalVariableCheck(GVBase() + "upper")) gUpperPrice = GlobalVariableGet(GVBase() + "upper");
   if(GlobalVariableCheck(GVBase() + "lower")) gLowerPrice = GlobalVariableGet(GVBase() + "lower");
   if(GlobalVariableCheck(GVBase() + "nextlot")) gNextLot = GlobalVariableGet(GVBase() + "nextlot");
   if(GlobalVariableCheck(GVBase() + "cycles")) gCycles = (int)GlobalVariableGet(GVBase() + "cycles");
   if(GlobalVariableCheck(GVBase() + "last")) gLastTriggered = (ENUM_ZZ_SIDE)GlobalVariableGet(GVBase() + "last");
   if(GlobalVariableCheck(GVBase() + "started")) gStarted = GlobalVariableGet(GVBase() + "started") > 0.5;
   if(GlobalVariableCheck(GVBase() + "pclose")) gPendingCloseAll = GlobalVariableGet(GVBase() + "pclose") > 0.5;
  }
//+------------------------------------------------------------------+
