//+------------------------------------------------------------------+
//|                                                       donjai.mq5 |
//|                                      Based on ZigZag Hedge Logic |
//|                                          Generated by AI         |
//+------------------------------------------------------------------+
#property copyright "donjai EA"
#property link      ""
#property version   "1.00"

#include <Trade\Trade.mqh>
#include <Trade\PositionInfo.mqh>
#include <Trade\SymbolInfo.mqh>
#include <Trade\OrderInfo.mqh>

enum ENUM_ABCD_START_MODE
  {
   USE_ABCD_ELSE_BUY=0, // Use ABCD, otherwise BUY
   ALWAYS_BUY=1,        // Always BUY
   ALWAYS_SELL=2,       // Always SELL
   STRICT_ABCD=3        // Strict ABCD only
  };

enum ENUM_LOT_MODE
  {
   LOT_ADD=0, // ADD mode
   LOT_MUL=1  // MUL mode
  };
  
enum ENUM_ZZ_SIDE
  {
   ZZ_NONE=0,
   ZZ_BUY=1,
   ZZ_SELL=-1
  };

//--- Inputs
input bool                 InpAutoStart               = true;
input double               InpStartLot                = 0.10;
input ENUM_ABCD_START_MODE InpABCDStartMode           = USE_ABCD_ELSE_BUY;
input int                  InpStepPoints              = 300;
input ENUM_LOT_MODE        InpLotMode                 = LOT_ADD;
input double               InpLotAdd                  = 0.10;
input double               InpLotMultiplier           = 2.0;
input int                  InpMaxCycles               = 0;
input bool                 InpCloseAllOnProfit        = false;
input double               InpProfitTargetMoney       = 50.0;
input bool                 InpCloseAllOnLoss          = false;
input double               InpLossLimitMoney          = -200.0;
input ulong                InpMagic                   = 20260210;
input int                  InpSidewayMinATRPoints     = 0;
input double               InpMaxLotLimit             = 0.0;
input bool                 InpFollowPriceForPending   = false;
input bool                 InpUseTerminalGlobalVar    = true;

input ENUM_TIMEFRAMES      InpABCDTimeframe           = PERIOD_CURRENT;
input int                  InpABCDLookbackBars        = 100;
input int                  InpABCDConfirmBars         = 2;
input int                  InpABCDMinLegPoints        = 50;

input int                  InpATRPeriod               = 14;

//--- Global Objects
CTrade         trade;
CPositionInfo  posInfo;
CSymbolInfo    symInfo;
COrderInfo     orderInfo;

int zigzagHandle = INVALID_HANDLE;
int atrHandle = INVALID_HANDLE;

//--- State Variables
double gUpperPrice = 0.0;
double gLowerPrice = 0.0;
ENUM_ZZ_SIDE gLastTriggered = ZZ_NONE;
double gNextLot = 0.0;
int gCycles = 0;
bool gStarted = false;
bool gPendingCloseAll = false;
bool gMarketWasClosed = false;
ENUM_ZZ_SIDE gAbcdSignal = ZZ_NONE;
bool gPausedBySideway = false;
bool gPausedByMaxLot = false;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
  {
   symInfo.Name(_Symbol);
   trade.SetExpertMagicNumber(InpMagic);
   
   atrHandle = iATR(_Symbol, PERIOD_CURRENT, InpATRPeriod);
   
   if(InpUseTerminalGlobalVar)
     LoadState();
     
   if(IsFlatNow())
     ResetSequenceStateIfFlat("OnInit: flat");
     
   EventSetTimer(1); // Timer every 1 second
   
   if(InpAutoStart && !gStarted)
     StartSequence();
     
   return(INIT_SUCCEEDED);
  }

void OnDeinit(const int reason)
  {
   if(InpUseTerminalGlobalVar)
     SaveState();
   EventKillTimer();
   if(zigzagHandle != INVALID_HANDLE) IndicatorRelease(zigzagHandle);
   if(atrHandle != INVALID_HANDLE) IndicatorRelease(atrHandle);
  }

void OnTimer()
  {
   HandleMarketOpenClose();
   if(IsFlatNow()) ResetSequenceStateIfFlat("OnTimer: flat");
   UpdateAbcdSignalIfNeeded();
   
   if(gPendingCloseAll)
      CheckProfitLossCloseAll(); // Retry close
      
   MaintainOppositePending();
  }

void OnTick()
  {
   if(!symInfo.RefreshRates()) return;
   
   HandleMarketOpenClose();
   if(IsFlatNow()) ResetSequenceStateIfFlat("OnTick: flat");
   UpdateAbcdSignalIfNeeded();
   
   if(InpAutoStart && IsFlatNow())
      StartSequence();
      
   if(gPendingCloseAll) return;
   
   if(InpMaxCycles > 0 && gCycles >= InpMaxCycles)
     {
      CancelAllPendings();
      CheckProfitLossCloseAll();
     }
     
   CheckProfitLossCloseAll();
   MaintainOppositePending();
  }

void OnTradeTransaction(const MqlTradeTransaction &trans, const MqlTradeRequest &request, const MqlTradeResult &result)
  {
   if(trans.type == TRADE_TRANSACTION_DEAL_ADD)
     {
      ulong ticket = trans.deal;
      if(HistoryDealSelect(ticket))
        {
         if(HistoryDealGetInteger(ticket, DEAL_MAGIC) == InpMagic && HistoryDealGetString(ticket, DEAL_SYMBOL) == _Symbol)
           {
            long entry = HistoryDealGetInteger(ticket, DEAL_ENTRY);
            if(entry == DEAL_ENTRY_IN)
              {
               long type = HistoryDealGetInteger(ticket, DEAL_TYPE);
               double vol = HistoryDealGetDouble(ticket, DEAL_VOLUME);
               
               if(type == DEAL_TYPE_BUY) gLastTriggered = ZZ_BUY;
               else if(type == DEAL_TYPE_SELL) gLastTriggered = ZZ_SELL;
               
               gCycles++;
               gNextLot = GetNextLot(vol);
               
               if(InpMaxCycles > 0 && gCycles >= InpMaxCycles)
                 {
                  CancelAllPendings();
                  SaveState();
                  return;
                 }
                 
               PlaceOppositeStop(gLastTriggered, gNextLot);
               SaveState();
              }
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| Core Logic Functions                                             |
//+------------------------------------------------------------------+

bool IsFlatNow()
  {
   return CountPositionsByMagic() == 0;
  }

int CountPositionsByMagic()
  {
   int count = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      if(posInfo.SelectByIndex(i))
        {
         if(posInfo.Magic() == InpMagic && posInfo.Symbol() == _Symbol)
            count++;
        }
     }
   return count;
  }

void ResetSequenceStateIfFlat(string reason)
  {
   CancelAllPendings();
   gStarted = false;
   gCycles = 0;
   gLastTriggered = ZZ_NONE;
   gUpperPrice = 0.0;
   gLowerPrice = 0.0;
   gNextLot = InpStartLot;
   gPendingCloseAll = false;
  }

void HandleMarketOpenClose()
  {
   // Basic mockup for session checks
   bool isOpen = (SymbolInfoInteger(_Symbol, SYMBOL_SESSION_DEALS) > 0);
   if(!isOpen && !gMarketWasClosed)
     {
      Print("Market closed.");
      gMarketWasClosed = true;
     }
   else if(isOpen && gMarketWasClosed)
     {
      gMarketWasClosed = false;
      if(IsFlatNow()) ResetSequenceStateIfFlat("Market Reopen");
      else if(gPendingCloseAll) CheckProfitLossCloseAll();
     }
  }

void UpdateAbcdSignalIfNeeded()
  {
   // For now, simplified logic indicating direction
   if(gAbcdSignal == ZZ_NONE)
     {
      if(InpABCDStartMode == ALWAYS_BUY) gAbcdSignal = ZZ_BUY;
      else if(InpABCDStartMode == ALWAYS_SELL) gAbcdSignal = ZZ_SELL;
      else gAbcdSignal = ZZ_BUY; // Default simplified
     }
  }

double GetNextLot(double lastVol)
  {
   double nextLot = lastVol;
   if(InpLotMode == LOT_ADD) nextLot += InpLotAdd;
   else if(InpLotMode == LOT_MUL) nextLot *= InpLotMultiplier;
   
   if(InpMaxLotLimit > 0 && nextLot > InpMaxLotLimit)
     {
      nextLot = InpMaxLotLimit;
      gPausedByMaxLot = true;
     }
     
   return NormalizeLot(nextLot);
  }

double NormalizeLot(double lots)
  {
   double step = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   double min = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double max = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
   double l = MathRound(lots / step) * step;
   if(l < min) l = min;
   if(l > max) l = max;
   return l;
  }

void PlaceOppositeStop(ENUM_ZZ_SIDE lastSide, double lots)
  {
   if(!symInfo.RefreshRates()) return;
   
   if(IsSidewayNow()) return;
   if(gPausedByMaxLot) return;
   
   lots = NormalizeLot(lots);
   
   if(lastSide == ZZ_BUY)
     {
      double price = gLowerPrice > 0 ? gLowerPrice : symInfo.Bid() - (InpStepPoints * _Point);
      if(symInfo.Bid() > price)
        {
         trade.SellStop(lots, price, _Symbol, 0, 0, ORDER_TIME_GTC, 0, "Opposite Sell Stop");
        }
     }
   else if(lastSide == ZZ_SELL)
     {
      double price = gUpperPrice > 0 ? gUpperPrice : symInfo.Ask() + (InpStepPoints * _Point);
      if(symInfo.Ask() < price)
        {
         trade.BuyStop(lots, price, _Symbol, 0, 0, ORDER_TIME_GTC, 0, "Opposite Buy Stop");
        }
     }
  }

void StartSequence()
  {
   if(!symInfo.RefreshRates()) return;
   if(IsSidewayNow()) return;
   
   UpdateAbcdSignalIfNeeded();
   
   double ask = symInfo.Ask();
   double bid = symInfo.Bid();
   
   if(gAbcdSignal == ZZ_BUY)
     {
      gUpperPrice = ask;
      gLowerPrice = ask - (InpStepPoints * _Point);
      trade.Buy(InpStartLot, _Symbol, ask, 0, 0, "Sequence Start Buy");
     }
   else if(gAbcdSignal == ZZ_SELL)
     {
      gLowerPrice = bid;
      gUpperPrice = bid + (InpStepPoints * _Point);
      trade.Sell(InpStartLot, _Symbol, bid, 0, 0, "Sequence Start Sell");
     }
     
   gStarted = true;
   SaveState();
  }

void MaintainOppositePending()
  {
   if(IsFlatNow()) return;
   if(IsSidewayNow())
     {
      CancelAllPendings();
      return;
     }
   if(gPausedByMaxLot)
     {
      CancelAllPendings();
      return;
     }
     
   int pendingCount = 0;
   for(int i = OrdersTotal() - 1; i >=0 ; i--)
     {
      ulong ticket = OrderGetTicket(i);
      if(OrderSelect(ticket))
        {
         if(OrderGetInteger(ORDER_MAGIC) == InpMagic && OrderGetString(ORDER_SYMBOL) == _Symbol)
            pendingCount++;
        }
     }
     
   if(pendingCount == 0 && gLastTriggered != ZZ_NONE && gNextLot > 0)
     {
      PlaceOppositeStop(gLastTriggered, gNextLot);
     }
  }

void CancelAllPendings()
  {
   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      ulong ticket = OrderGetTicket(i);
      if(OrderSelect(ticket))
        {
         if(OrderGetInteger(ORDER_MAGIC) == InpMagic && OrderGetString(ORDER_SYMBOL) == _Symbol)
           {
            trade.OrderDelete(ticket);
           }
        }
     }
  }

void CheckProfitLossCloseAll()
  {
   if(!InpCloseAllOnProfit && !InpCloseAllOnLoss) return;
   
   double totalFloat = FloatingProfitByMagic();
   
   bool closeCondition = false;
   if(InpCloseAllOnProfit && totalFloat >= InpProfitTargetMoney) closeCondition = true;
   if(InpCloseAllOnLoss && totalFloat <= InpLossLimitMoney) closeCondition = true;
   
   if(closeCondition)
     {
      CancelAllPendings();
      for(int i = PositionsTotal() - 1; i >= 0; i--)
        {
         if(posInfo.SelectByIndex(i))
           {
            if(posInfo.Magic() == InpMagic && posInfo.Symbol() == _Symbol)
              {
               trade.PositionClose(posInfo.Ticket());
              }
           }
        }
      gPendingCloseAll = false;
     }
  }

double FloatingProfitByMagic()
  {
   double profit = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      if(posInfo.SelectByIndex(i))
        {
         if(posInfo.Magic() == InpMagic && posInfo.Symbol() == _Symbol)
           {
            profit += posInfo.Profit() + posInfo.Swap();
           }
        }
     }
   return profit;
  }

bool IsSidewayNow()
  {
   if(InpSidewayMinATRPoints <= 0) return false;
   if(atrHandle == INVALID_HANDLE) return false;
   double atr[];
   if(CopyBuffer(atrHandle, 0, 1, 1, atr) > 0)
     {
      double atrPts = atr[0] / _Point;
      if(atrPts < InpSidewayMinATRPoints)
        {
         gPausedBySideway = true;
         return true;
        }
     }
   gPausedBySideway = false;
   return false;
  }

//+------------------------------------------------------------------+
//| State Persistence                                                |
//+------------------------------------------------------------------+
string GVBase()
  {
   return "ZZH2LV8_" + _Symbol + "_" + IntegerToString(InpMagic) + "_";
  }

void SaveState()
  {
   if(!InpUseTerminalGlobalVar) return;
   GlobalVariableSet(GVBase() + "upper", gUpperPrice);
   GlobalVariableSet(GVBase() + "lower", gLowerPrice);
   GlobalVariableSet(GVBase() + "nextlot", gNextLot);
   GlobalVariableSet(GVBase() + "cycles", gCycles);
   GlobalVariableSet(GVBase() + "last", (double)gLastTriggered);
   GlobalVariableSet(GVBase() + "started", gStarted ? 1.0 : 0.0);
   GlobalVariableSet(GVBase() + "pclose", gPendingCloseAll ? 1.0 : 0.0);
  }

void LoadState()
  {
   if(!InpUseTerminalGlobalVar) return;
   
   if(GlobalVariableCheck(GVBase() + "upper")) gUpperPrice = GlobalVariableGet(GVBase() + "upper");
   if(GlobalVariableCheck(GVBase() + "lower")) gLowerPrice = GlobalVariableGet(GVBase() + "lower");
   if(GlobalVariableCheck(GVBase() + "nextlot")) gNextLot = GlobalVariableGet(GVBase() + "nextlot");
   if(GlobalVariableCheck(GVBase() + "cycles")) gCycles = (int)GlobalVariableGet(GVBase() + "cycles");
   if(GlobalVariableCheck(GVBase() + "last")) gLastTriggered = (ENUM_ZZ_SIDE)GlobalVariableGet(GVBase() + "last");
   if(GlobalVariableCheck(GVBase() + "started")) gStarted = GlobalVariableGet(GVBase() + "started") > 0.5;
   if(GlobalVariableCheck(GVBase() + "pclose")) gPendingCloseAll = GlobalVariableGet(GVBase() + "pclose") > 0.5;
  }
//+------------------------------------------------------------------+
